import PDFDocument from 'pdfkit';
import { Response } from 'express';

function money(n: number): string {
  return (n || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

export function generateW2Pdf(w2: any, res: Response) {
  const doc = new PDFDocument({ size: 'LETTER', margin: 36 });
  doc.pipe(res);

  // Header
  doc.fontSize(18).font('Helvetica-Bold').text('Form W-2', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text('Wage and Tax Statement', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(9).text(`Tax Year ${w2.taxYear}`, { align: 'center' });
  doc.moveDown(1);

  // Employer section
  doc.fontSize(10).font('Helvetica-Bold').text('Employer information');
  doc.fontSize(9).font('Helvetica');
  doc.text(`Company: ${w2.companyName || ''}`);
  doc.text(`EIN: ${w2.companyEin || '____________________'}`);
  doc.text(`Address: ${w2.companyAddress || ''}`);
  doc.moveDown(0.5);

  // Employee section
  doc.fontSize(10).font('Helvetica-Bold').text('Employee information');
  doc.fontSize(9).font('Helvetica');
  doc.text(`Name: ${w2.firstName} ${w2.lastName}`);
  doc.text(`SSN: XXX-XX-${w2.ssnLast4 || '____'}`);
  doc.text(`Address: ${w2.address || ''}`);
  doc.moveDown(1);

  // Boxes
  const boxRow = (label: string, box: string, value: string, y: number) => {
    doc.rect(36, y, 540, 28).stroke();
    doc.fontSize(8).font('Helvetica-Bold').text(`Box ${box}`, 40, y + 4, { width: 40 });
    doc.fontSize(7).font('Helvetica').text(label, 80, y + 4, { width: 380 });
    doc.fontSize(10).font('Helvetica-Bold').text(value, 460, y + 6, { width: 110, align: 'right' });
  };

  let y = doc.y + 10;
  boxRow('Wages, tips, other compensation', '1', money(w2.wages), y);
  y += 30;
  boxRow('Federal income tax withheld', '2', money(w2.fedTax), y);
  y += 30;
  boxRow('Social security wages', '3', money(w2.ssWages), y);
  y += 30;
  boxRow('Social security tax withheld', '4', money(w2.ssTax), y);
  y += 30;
  boxRow('Medicare wages and tips', '5', money(w2.medWages), y);
  y += 30;
  boxRow('Medicare tax withheld', '6', money(w2.medTax), y);
  y += 30;
  boxRow('State wages', '16', money(w2.stateWages), y);
  y += 30;
  boxRow('State income tax', '17', money(w2.stateTax), y);

  // Footer
  doc.moveDown(2);
  doc.fontSize(7).font('Helvetica-Oblique').fillColor('#666666').text(
    'This is a draft/preview generated by AURA Accounting. ' +
    'For actual filing, use the official IRS W-2 forms and SSA e-filing. ' +
    'Verify all amounts before distributing to employees.',
    { align: 'center', width: 540 }
  );

  doc.end();
}

export function generate1099Pdf(f: any, res: Response) {
  const doc = new PDFDocument({ size: 'LETTER', margin: 36 });
  doc.pipe(res);

  doc.fontSize(18).font('Helvetica-Bold').text(`Form 1099-${f.formType}`, { align: 'center' });
  doc.fontSize(10).font('Helvetica').text('Miscellaneous Income', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(9).text(`Tax Year ${f.taxYear}`, { align: 'center' });
  doc.moveDown(1);

  // Payer
  doc.fontSize(10).font('Helvetica-Bold').text('Payer information');
  doc.fontSize(9).font('Helvetica');
  doc.text(`Company: ${f.companyName || ''}`);
  doc.text(`EIN: ${f.companyEin || '____________________'}`);
  doc.text(`Address: ${f.companyAddress || ''}`);
  doc.moveDown(0.5);

  // Recipient
  doc.fontSize(10).font('Helvetica-Bold').text('Recipient information');
  doc.fontSize(9).font('Helvetica');
  const recipientName = f.businessName
    ? `${f.businessName} (${f.firstName} ${f.lastName})`
    : `${f.firstName} ${f.lastName}`;
  doc.text(`Name: ${recipientName}`);
  doc.text(`${f.tinType.toUpperCase()}: XXX-XX-${f.tinLast4 || '____'}`);
  doc.text(`Address: ${f.address || ''}`);
  doc.moveDown(1);

  const boxRow = (label: string, box: string, value: string, y: number) => {
    doc.rect(36, y, 540, 32).stroke();
    doc.fontSize(8).font('Helvetica-Bold').text(`Box ${box}`, 40, y + 4, { width: 40 });
    doc.fontSize(7).font('Helvetica').text(label, 80, y + 4, { width: 380 });
    doc.fontSize(10).font('Helvetica-Bold').text(value, 460, y + 8, { width: 110, align: 'right' });
  };

  let y = doc.y + 10;
  boxRow('Nonemployee compensation', '1', money(f.box1NonemployeeComp), y);
  y += 34;
  boxRow('Direct sales (see instructions)', '2', money(f.box2DirectSales), y);
  y += 34;
  boxRow('Total (sum of boxes 1, 2)', '3', money(f.box3), y);
  y += 34;
  boxRow('Federal income tax withheld', '4', money(f.box4FedTax), y);

  doc.moveDown(3);
  doc.fontSize(7).font('Helvetica-Oblique').fillColor('#666666').text(
    'This is a draft/preview generated by AURA Accounting. ' +
    'For actual IRS filing, use Form 1099-NEC official layout and IRS FIRE system. ' +
    'A 1099-NEC must be filed for any contractor paid $600 or more in a calendar year.',
    { align: 'center', width: 540 }
  );

  doc.end();
}
